/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.UsersLinksRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersLinks extends TableImpl<UsersLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>USERS_LINKS</code>
     */
    public static final UsersLinks USERS_LINKS = new UsersLinks();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<UsersLinksRecord> getRecordType() {
        return UsersLinksRecord.class;
    }

    /**
     * The column <code>USERS_LINKS.ID</code>.
     */
    public final TableField<UsersLinksRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>USERS_LINKS.USER_ID</code>.
     */
    public final TableField<UsersLinksRecord, Long> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>USERS_LINKS.LINK_ID</code>.
     */
    public final TableField<UsersLinksRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>USERS_LINKS.DELETED_AT</code>.
     */
    public final TableField<UsersLinksRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private UsersLinks(Name alias, Table<UsersLinksRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersLinks(Name alias, Table<UsersLinksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>USERS_LINKS</code> table reference
     */
    public UsersLinks(String alias) {
        this(DSL.name(alias), USERS_LINKS);
    }

    /**
     * Create an aliased <code>USERS_LINKS</code> table reference
     */
    public UsersLinks(Name alias) {
        this(alias, USERS_LINKS);
    }

    /**
     * Create a <code>USERS_LINKS</code> table reference
     */
    public UsersLinks() {
        this(DSL.name("USERS_LINKS"), null);
    }

    public <O extends Record> UsersLinks(Table<O> child, ForeignKey<O, UsersLinksRecord> key) {
        super(child, key, USERS_LINKS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<UsersLinksRecord, Long> getIdentity() {
        return (Identity<UsersLinksRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<UsersLinksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    @NotNull
    public List<ForeignKey<UsersLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_C6, Keys.CONSTRAINT_C67);
    }

    private transient Users _users;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.USERS</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.CONSTRAINT_C6);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.CONSTRAINT_C67);

        return _links;
    }

    @Override
    @NotNull
    public UsersLinks as(String alias) {
        return new UsersLinks(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public UsersLinks as(Name alias) {
        return new UsersLinks(alias, this);
    }

    @Override
    @NotNull
    public UsersLinks as(Table<?> alias) {
        return new UsersLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersLinks rename(String name) {
        return new UsersLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersLinks rename(Name name) {
        return new UsersLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersLinks rename(Table<?> name) {
        return new UsersLinks(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Long, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
