/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.LinksSites;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksSitesRecord extends UpdatableRecordImpl<LinksSitesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS_SITES.ID</code>.
     */
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS_SITES.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LINKS_SITES.SITE_NAME</code>.
     */
    public void setSiteName(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS_SITES.SITE_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getSiteName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return LinksSites.LINKS_SITES.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return LinksSites.LINKS_SITES.SITE_NAME;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getSiteName();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getSiteName();
    }

    @Override
    @NotNull
    public LinksSitesRecord value1(@NotNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSitesRecord value2(@NotNull String value) {
        setSiteName(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSitesRecord values(@NotNull Integer value1, @NotNull String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksSitesRecord
     */
    public LinksSitesRecord() {
        super(LinksSites.LINKS_SITES);
    }

    /**
     * Create a detached, initialised LinksSitesRecord
     */
    @ConstructorProperties({ "id", "siteName" })
    public LinksSitesRecord(@NotNull Integer id, @NotNull String siteName) {
        super(LinksSites.LINKS_SITES);

        setId(id);
        setSiteName(siteName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinksSitesRecord
     */
    public LinksSitesRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.LinksSites value) {
        super(LinksSites.LINKS_SITES);

        if (value != null) {
            setId(value.getId());
            setSiteName(value.getSiteName());
            resetChangedOnNotNull();
        }
    }
}
