/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksRecord extends UpdatableRecordImpl<LinksRecord> implements Record9<Long, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINKS.ADDED_AT</code>.
     */
    public void setAddedAt(@NotNull OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS.ADDED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getAddedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>LINKS.UPDATED_AT</code>.
     */
    public void setUpdatedAt(@NotNull OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINKS.UPDATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>LINKS.DELETED_AT</code>.
     */
    public void setDeletedAt(@Nullable OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINKS.DELETED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>LINKS.LAST_ACTIVITY</code>.
     */
    public void setLastActivity(@NotNull OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINKS.LAST_ACTIVITY</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastActivity() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>LINKS.SITE_ID</code>.
     */
    public void setSiteId(@NotNull Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>LINKS.SITE_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getSiteId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>LINKS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>LINKS.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>LINKS.COMMENT_COUNT</code>.
     */
    public void setCommentCount(@Nullable Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>LINKS.COMMENT_COUNT</code>.
     */
    @Nullable
    public Integer getCommentCount() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row9<Long, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row9<Long, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Links.LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Links.LINKS.URL;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field3() {
        return Links.LINKS.ADDED_AT;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return Links.LINKS.UPDATED_AT;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field5() {
        return Links.LINKS.DELETED_AT;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field6() {
        return Links.LINKS.LAST_ACTIVITY;
    }

    @Override
    @NotNull
    public Field<Integer> field7() {
        return Links.LINKS.SITE_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field8() {
        return Links.LINKS.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field9() {
        return Links.LINKS.COMMENT_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @NotNull
    public OffsetDateTime component3() {
        return getAddedAt();
    }

    @Override
    @NotNull
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    @NotNull
    public OffsetDateTime component6() {
        return getLastActivity();
    }

    @Override
    @NotNull
    public Integer component7() {
        return getSiteId();
    }

    @Override
    @Nullable
    public Integer component8() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer component9() {
        return getCommentCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @NotNull
    public OffsetDateTime value3() {
        return getAddedAt();
    }

    @Override
    @NotNull
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    @NotNull
    public OffsetDateTime value6() {
        return getLastActivity();
    }

    @Override
    @NotNull
    public Integer value7() {
        return getSiteId();
    }

    @Override
    @Nullable
    public Integer value8() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer value9() {
        return getCommentCount();
    }

    @Override
    @NotNull
    public LinksRecord value1(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value3(@NotNull OffsetDateTime value) {
        setAddedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value4(@NotNull OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value5(@Nullable OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value6(@NotNull OffsetDateTime value) {
        setLastActivity(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value7(@NotNull Integer value) {
        setSiteId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value8(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value9(@Nullable Integer value) {
        setCommentCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord values(@Nullable Long value1, @NotNull String value2, @NotNull OffsetDateTime value3, @NotNull OffsetDateTime value4, @Nullable OffsetDateTime value5, @NotNull OffsetDateTime value6, @NotNull Integer value7, @Nullable Integer value8, @Nullable Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    @ConstructorProperties({ "linkId", "url", "addedAt", "updatedAt", "deletedAt", "lastActivity", "siteId", "answerCount", "commentCount" })
    public LinksRecord(@Nullable Long linkId, @NotNull String url, @NotNull OffsetDateTime addedAt, @NotNull OffsetDateTime updatedAt, @Nullable OffsetDateTime deletedAt, @NotNull OffsetDateTime lastActivity, @NotNull Integer siteId, @Nullable Integer answerCount, @Nullable Integer commentCount) {
        super(Links.LINKS);

        setLinkId(linkId);
        setUrl(url);
        setAddedAt(addedAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setLastActivity(lastActivity);
        setSiteId(siteId);
        setAnswerCount(answerCount);
        setCommentCount(commentCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Links value) {
        super(Links.LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setUrl(value.getUrl());
            setAddedAt(value.getAddedAt());
            setUpdatedAt(value.getUpdatedAt());
            setDeletedAt(value.getDeletedAt());
            setLastActivity(value.getLastActivity());
            setSiteId(value.getSiteId());
            setAnswerCount(value.getAnswerCount());
            setCommentCount(value.getCommentCount());
            resetChangedOnNotNull();
        }
    }
}
