/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.UsersLinks;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersLinksRecord extends UpdatableRecordImpl<UsersLinksRecord> implements Record4<Long, Long, Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>USERS_LINKS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>USERS_LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>USERS_LINKS.USER_ID</code>.
     */
    public void setUserId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>USERS_LINKS.USER_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>USERS_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>USERS_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>USERS_LINKS.DELETED_AT</code>.
     */
    public void setDeletedAt(@Nullable OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>USERS_LINKS.DELETED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Long, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Long, Long, Long, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return UsersLinks.USERS_LINKS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return UsersLinks.USERS_LINKS.USER_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return UsersLinks.USERS_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return UsersLinks.USERS_LINKS.DELETED_AT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getUserId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime component4() {
        return getDeletedAt();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getUserId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime value4() {
        return getDeletedAt();
    }

    @Override
    @NotNull
    public UsersLinksRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord value2(@NotNull Long value) {
        setUserId(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord value3(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord value4(@Nullable OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord values(@Nullable Long value1, @NotNull Long value2, @NotNull Long value3, @Nullable OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersLinksRecord
     */
    public UsersLinksRecord() {
        super(UsersLinks.USERS_LINKS);
    }

    /**
     * Create a detached, initialised UsersLinksRecord
     */
    @ConstructorProperties({ "id", "userId", "linkId", "deletedAt" })
    public UsersLinksRecord(@Nullable Long id, @NotNull Long userId, @NotNull Long linkId, @Nullable OffsetDateTime deletedAt) {
        super(UsersLinks.USERS_LINKS);

        setId(id);
        setUserId(userId);
        setLinkId(linkId);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersLinksRecord
     */
    public UsersLinksRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.UsersLinks value) {
        super(UsersLinks.USERS_LINKS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setLinkId(value.getLinkId());
            setDeletedAt(value.getDeletedAt());
            resetChangedOnNotNull();
        }
    }
}
