app:
  bot-url: http://localhost:8090
  database-access-type: JDBC
  links-to-update: 2

  retry-policy:
    type: constant
    attempts: 3
    backoff: 30s
    httpStatusCodes:
      - 404

github-client:
  base-url: https://api.github.com
  retry-policy:
    type: constant
    attempts: 3
    backoff: 30s
    httpStatusCodes:
      - 404

stackoverflow-client:
  base-url: https://api.stackexchange.com/2.3
  retry-policy:
    type: constant
    attempts: 3
    backoff: 30s
    httpStatusCodes:
      - 404

scheduler:
  enable: true
  interval: 30m
  force-check-delay: 60m

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml

resources:
  supported-resources:
    "[stackoverflow.com]":
      id: 1
      base-url: https://api.stackexchange.com/2.3
      url-pattern: ^https?://stackoverflow\.com/.*/(.*)/.*$

    "[github.com]":
      id: 2
      base-url: https://api.github.com
      url-pattern: ^https?://github\.com/(.*)/(.*)$

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  server:
    port: 8081
  metrics:
    tags:
      application: ${spring.application.name}
