app:
  bot-url: "http://localhost:8090"
  github-baseurl: "https://api.github.com"
  stackoverflow-baseurl: "https://api.stackexchange.com/2.3"
  kafka-url: "http://localhost:29091"
  use-queue: false

scheduler:
  enable: true
  interval: 10s
  force-check-delay: 10000

spring:
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
