app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-url: http://localhost:8080

  retry-policy:
    type: constant
    attempts: 3
    backoff: 30s
    httpStatusCodes:
      - 404

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    activate:
      on-profile: default

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
