app:
  telegram-token: 6599368560:AAGJCXu83Q1MS4_Qu0g1oUNDRPePgG_UeQQ

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
