app:
  telegram-token: "${TELEGRAM_TOKEN}"
  scrapper-url: "http://scrapper:8080"

  retry-policy:
    type: constant
    attempts: 3
    backoff: 30s
    httpStatusCodes:
      - 404

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    activate:
      on-profile: default
  kafka:
    bootstrap-servers: "localhost:29091" # for github build
#    bootstrap-servers: "http://kafka:9091"    # for actual work

  cache:
    cache-names:
    - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: .*
    http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: "classpath:log4j2-plain.xml"

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  server:
    port: 8091
  metrics:
    tags:
      application: "${spring.application.name}"
