/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables;


import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.UsersArchiveRecord;

import java.time.OffsetDateTime;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersArchive extends TableImpl<UsersArchiveRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>USERS_ARCHIVE</code>
     */
    public static final UsersArchive USERS_ARCHIVE = new UsersArchive();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<UsersArchiveRecord> getRecordType() {
        return UsersArchiveRecord.class;
    }

    /**
     * The column <code>USERS_ARCHIVE.ID</code>.
     */
    public final TableField<UsersArchiveRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>USERS_ARCHIVE.TG_CHAT_ID</code>.
     */
    public final TableField<UsersArchiveRecord, Long> TG_CHAT_ID = createField(DSL.name("TG_CHAT_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>USERS_ARCHIVE.ADDED_AT</code>.
     */
    public final TableField<UsersArchiveRecord, OffsetDateTime> ADDED_AT = createField(DSL.name("ADDED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>USERS_ARCHIVE.DELETED_AT</code>.
     */
    public final TableField<UsersArchiveRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private UsersArchive(Name alias, Table<UsersArchiveRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersArchive(Name alias, Table<UsersArchiveRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>USERS_ARCHIVE</code> table reference
     */
    public UsersArchive(String alias) {
        this(DSL.name(alias), USERS_ARCHIVE);
    }

    /**
     * Create an aliased <code>USERS_ARCHIVE</code> table reference
     */
    public UsersArchive(Name alias) {
        this(alias, USERS_ARCHIVE);
    }

    /**
     * Create a <code>USERS_ARCHIVE</code> table reference
     */
    public UsersArchive() {
        this(DSL.name("USERS_ARCHIVE"), null);
    }

    public <O extends Record> UsersArchive(Table<O> child, ForeignKey<O, UsersArchiveRecord> key) {
        super(child, key, USERS_ARCHIVE);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<UsersArchiveRecord, Long> getIdentity() {
        return (Identity<UsersArchiveRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<UsersArchiveRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    @NotNull
    public UsersArchive as(String alias) {
        return new UsersArchive(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public UsersArchive as(Name alias) {
        return new UsersArchive(alias, this);
    }

    @Override
    @NotNull
    public UsersArchive as(Table<?> alias) {
        return new UsersArchive(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersArchive rename(String name) {
        return new UsersArchive(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersArchive rename(Name name) {
        return new UsersArchive(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UsersArchive rename(Table<?> name) {
        return new UsersArchive(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
