/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.LinksSites;
import edu.java.scrapper.domain.jooq.tables.Users;
import edu.java.scrapper.domain.jooq.tables.UsersArchive;
import edu.java.scrapper.domain.jooq.tables.UsersLinks;
import edu.java.scrapper.domain.jooq.tables.UsersLinksArchive;
import edu.java.scrapper.domain.jooq.tables.records.LinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinksSitesRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersArchiveRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersLinksArchiveRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersLinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksSitesRecord> CONSTRAINT_46 = Internal.createUniqueKey(LinksSites.LINKS_SITES, DSL.name("CONSTRAINT_46"), new TableField[] { LinksSites.LINKS_SITES.ID }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_4 = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_4"), new TableField[] { Users.USERS.TG_CHAT_ID }, true);
    public static final UniqueKey<UsersArchiveRecord> CONSTRAINT_A = Internal.createUniqueKey(UsersArchive.USERS_ARCHIVE, DSL.name("CONSTRAINT_A"), new TableField[] { UsersArchive.USERS_ARCHIVE.ID }, true);
    public static final UniqueKey<UsersLinksRecord> CONSTRAINT_AD64 = Internal.createUniqueKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_AD64"), new TableField[] { UsersLinks.USERS_LINKS.USER_ID, UsersLinks.USERS_LINKS.LINK_ID }, true);
    public static final UniqueKey<UsersLinksArchiveRecord> CONSTRAINT_8 = Internal.createUniqueKey(UsersLinksArchive.USERS_LINKS_ARCHIVE, DSL.name("CONSTRAINT_8"), new TableField[] { UsersLinksArchive.USERS_LINKS_ARCHIVE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksRecord, LinksSitesRecord> FL_LINKS_SITES = Internal.createForeignKey(Links.LINKS, DSL.name("FL_LINKS_SITES"), new TableField[] { Links.LINKS.SITE_ID }, Keys.CONSTRAINT_46, new TableField[] { LinksSites.LINKS_SITES.ID }, true);
    public static final ForeignKey<UsersLinksRecord, UsersRecord> CONSTRAINT_AD = Internal.createForeignKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_AD"), new TableField[] { UsersLinks.USERS_LINKS.USER_ID }, Keys.CONSTRAINT_4, new TableField[] { Users.USERS.TG_CHAT_ID }, true);
    public static final ForeignKey<UsersLinksRecord, LinksRecord> CONSTRAINT_AD6 = Internal.createForeignKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_AD6"), new TableField[] { UsersLinks.USERS_LINKS.LINK_ID }, Keys.CONSTRAINT_45, new TableField[] { Links.LINKS.ID }, true);
}
