/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import javax.annotation.processing.Generated;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.LinksSites;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Users;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.UsersLinks;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>LINKS_SITES</code>.
     */
    public static final LinksSites LINKS_SITES = LinksSites.LINKS_SITES;

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>USERS_LINKS</code>.
     */
    public static final UsersLinks USERS_LINKS = UsersLinks.USERS_LINKS;
}
